import type { College, StudentProfile } from "../src/lib/types";
import { DEFAULT_WEIGHTS } from "../src/lib/types";

export function makeStudent(overrides: Partial<StudentProfile> = {}): StudentProfile {
  return {
    firstName: "Test",
    graduationYear: 2027,
    homeState: "MD",
    homeZip: "20814",
    gpaWeighted: 4.1,
    gpaUnweighted: 3.7,
    actComposite: 29,
    actSuperscore: 30,
    satScore: null,
    apCourses: 5,
    ibCourses: 0,
    honorsCourses: 4,
    dualEnrollmentCourses: 0,
    intendedMajors: ["Computer Science"],
    householdIncomeRange: "75001_110000",
    familySize: 4,
    maxAnnualBudget: 25000,
    preferredStates: ["MD", "VA"],
    preferredRegions: ["Mid-Atlantic"],
    schoolTypePreference: "any",
    campusSizePreference: "any",
    settingPreference: "any",
    ncaaPreference: "any",
    extracurriculars: [],
    applicationPlanPreference: "any",
    scoreWeights: { ...DEFAULT_WEIGHTS },
    isSample: true,
    ...overrides,
  };
}

export function makeCollege(overrides: Partial<College> = {}): College {
  return {
    id: "test-college",
    name: "Test University",
    city: "Testville",
    state: "MD",
    zip: "21201",
    latitude: 39.29,
    longitude: -76.61,
    website: "https://example.edu",
    admissionsUrl: "https://example.edu/admissions",
    netPriceCalculatorUrl: "https://example.edu/npc",
    ownership: "public",
    level: "four_year",
    enrollment: 20000,
    campusSetting: "urban",
    ncaaDivision: "I",
    acceptanceRate: 0.55,
    act25: 26,
    act75: 31,
    sat25: 1230,
    sat75: 1420,
    testPolicy: "optional",
    graduationRate: 0.8,
    retentionRate: 0.9,
    tuitionInState: 10000,
    tuitionOutState: 30000,
    fees: 2000,
    housingMeals: 13000,
    books: 1200,
    transportation: 1000,
    personalExpenses: 1800,
    avgNetPrice: 18000,
    netPriceByIncome: null,
    avgGrantAid: 8000,
    medianFederalDebt: 20000,
    medianEarnings10yr: 65000,
    demographics: null,
    pellGrantRate: null,
    genderShares: null,
    majorShares: null,
    majors: ["Computer Science", "Biology"],
    applicationFee: 70,
    deadlines: [],
    requirements: [],
    financialAid: null,
    provenance: {
      sourceName: "Test",
      sourceUrl: "https://example.edu",
      dataYear: "2023-24",
      lastVerified: "2026-07-01",
      isSample: true,
    },
    isSample: true,
    ...overrides,
  };
}
