/**
 * Bundled colleges.
 * 1) Fictional SAMPLE institutions (isSample: true, "Sample data" badge) so the
 *    app works without a College Scorecard API key.
 * 2) A few PRELOADED real universities (isSample: false) built from published
 *    2023-24 College Scorecard / IPEDS figures. Their ids are real IPEDS unit
 *    ids so live Scorecard lookups resolve to the same record. Values may lag
 *    current figures — every section carries provenance and a verify link, and
 *    anything not confidently sourced is left null ("Not reported").
 */
import type { College, CollegeDeadline, ApplicationRequirement, Provenance } from "@/lib/types";

const SAMPLE_PROV = (section: string): Provenance => ({
  sourceName: `Sample dataset (${section})`,
  sourceUrl: "https://collegescorecard.ed.gov/",
  dataYear: "2023-24 (sample)",
  lastVerified: "2026-07-01",
  isSample: true,
});

const STD_REQS: ApplicationRequirement[] = [
  { key: "application", label: "Application form", required: true },
  { key: "fee", label: "Application fee or waiver", required: true },
  { key: "essay", label: "Personal essay", required: true },
  { key: "transcript", label: "Official transcript", required: true },
  { key: "counselor", label: "Counselor report", required: true },
  { key: "recommendations", label: "Teacher recommendations (2)", required: true },
  { key: "test_scores", label: "Test scores (per policy)", required: false },
  { key: "fafsa", label: "FAFSA", required: true },
];

function dl(
  collegeId: string,
  plan: CollegeDeadline["plan"],
  label: string,
  dueDate: string | null,
): CollegeDeadline {
  return {
    id: `${collegeId}-${plan}-${label.replace(/\s+/g, "-").toLowerCase()}`,
    collegeId,
    plan,
    label,
    dueDate,
    provenance: SAMPLE_PROV("deadlines"),
    mayHaveChanged: true,
  };
}


/** SAMPLE ONLY: deterministic descending degree shares for a sample college's majors. */
function sampleShares(names: string[]): { name: string; share: number }[] {
  const weights = names.map((_, i) => 1 / (i + 1.5));
  const total = weights.reduce((a, b) => a + b, 0);
  return names.map((name, i) => ({ name, share: Number((weights[i] / total).toFixed(3)) }));
}


/** Provenance for PRELOADED real colleges (not samples). */
const REAL_PROV = (section: string, scorecardId: string): Provenance => ({
  sourceName: `College Scorecard / IPEDS, preloaded (${section})`,
  sourceUrl: `https://collegescorecard.ed.gov/school/?${scorecardId}`,
  dataYear: "2023-24",
  lastVerified: "2026-07-22",
  isSample: false,
});

/** Deadline for a PRELOADED real college — standing cycle dates; always re-verify. */
function rdl(
  collegeId: string,
  plan: CollegeDeadline["plan"],
  label: string,
  dueDate: string | null,
  admissionsUrl: string,
): CollegeDeadline {
  return {
    id: `${collegeId}-${plan}-${label.replace(/\s+/g, "-").toLowerCase()}`,
    collegeId,
    plan,
    label,
    dueDate,
    provenance: {
      sourceName: "University admissions site (preloaded — verify current cycle)",
      sourceUrl: admissionsUrl,
      dataYear: "2026-27 cycle",
      lastVerified: "2026-07-22",
      isSample: false,
    },
    mayHaveChanged: true,
  };
}

export const SEED_COLLEGES: College[] = [
  {
    id: "163286",
    name: "University of Maryland, College Park",
    city: "College Park", state: "MD", zip: "20742",
    latitude: 38.9869, longitude: -76.9426,
    website: "https://www.umd.edu",
    admissionsUrl: "https://admissions.umd.edu",
    netPriceCalculatorUrl: null,
    ownership: "public", level: "four_year",
    enrollment: 30300, campusSetting: "suburban", ncaaDivision: "I",
    acceptanceRate: 0.45,
    act25: 30, act75: 34, sat25: 1330, sat75: 1510,
    testPolicy: "optional",
    graduationRate: 0.89, retentionRate: 0.95,
    tuitionInState: 11505, tuitionOutState: 40306,
    fees: null, housingMeals: 15000, books: null, transportation: null, personalExpenses: null,
    avgNetPrice: 18900,
    netPriceByIncome: null,
    avgGrantAid: null, medianFederalDebt: null, medianEarnings10yr: 75000,
    majors: ["Computer Science", "Engineering", "Biology", "Business", "Criminology", "Economics", "Public Health", "Psychology"],
    majorShares: null,
    demographics: { white: 0.42, asian: 0.21, black: 0.12, hispanic: 0.11, two_or_more: 0.05, non_resident: 0.04, unknown: 0.04 },
    genderShares: { men: 0.52, women: 0.48 },
    pellGrantRate: 0.17,
    applicationFee: 75,
    deadlines: [
      rdl("163286", "early_action", "Early Action application", "2026-11-01", "https://admissions.umd.edu"),
      rdl("163286", "regular", "Regular Decision application", "2027-01-20", "https://admissions.umd.edu"),
      rdl("163286", "scholarship", "Merit scholarship consideration (apply Early Action)", "2026-11-01", "https://admissions.umd.edu"),
    ],
    requirements: STD_REQS,
    financialAid: {
      scholarshipDisplacementPolicy:
        "Maryland was the first state to restrict scholarship displacement: public institutions generally may not reduce institutional grant aid because of outside scholarships unless total aid exceeds the cost of attendance. Confirm details with the aid office.",
      requiresFafsa: true, requiresCssProfile: false, priorityAidDeadline: null,
      meetsFullNeed: false, needBlind: null, meritAidAvailable: true,
      notes: "Apply Early Action for full merit-scholarship consideration.",
      provenance: REAL_PROV("financial aid", "163286"),
    },
    provenance: REAL_PROV("institution", "163286"),
    isSample: false,
  },
  {
    id: "214777",
    name: "Penn State University Park",
    city: "University Park", state: "PA", zip: "16802",
    latitude: 40.7982, longitude: -77.86,
    website: "https://www.psu.edu",
    admissionsUrl: "https://admissions.psu.edu",
    netPriceCalculatorUrl: null,
    ownership: "public", level: "four_year",
    enrollment: 41700, campusSetting: "rural", ncaaDivision: "I",
    acceptanceRate: 0.54,
    act25: 28, act75: 33, sat25: 1270, sat75: 1450,
    testPolicy: "optional",
    graduationRate: 0.86, retentionRate: 0.93,
    tuitionInState: 19835, tuitionOutState: 40188,
    fees: null, housingMeals: 13000, books: null, transportation: null, personalExpenses: null,
    avgNetPrice: 31000,
    netPriceByIncome: null,
    avgGrantAid: null, medianFederalDebt: null, medianEarnings10yr: 66000,
    majors: ["Engineering", "Business", "Biology", "Computer Science", "Communications", "Nursing", "Psychology", "Economics"],
    majorShares: null,
    demographics: { white: 0.62, asian: 0.1, hispanic: 0.08, black: 0.05, two_or_more: 0.04, non_resident: 0.09, unknown: 0.02 },
    genderShares: { men: 0.52, women: 0.48 },
    pellGrantRate: 0.14,
    applicationFee: 65,
    deadlines: [
      rdl("214777", "early_action", "Early Action application", "2026-11-01", "https://admissions.psu.edu"),
      rdl("214777", "rolling", "Rolling admission (apply early for best consideration)", null, "https://admissions.psu.edu"),
    ],
    requirements: STD_REQS,
    financialAid: {
      scholarshipDisplacementPolicy: null,
      requiresFafsa: true, requiresCssProfile: false, priorityAidDeadline: null,
      meetsFullNeed: false, needBlind: null, meritAidAvailable: true,
      notes: "Institutional grant aid is comparatively limited; net price for out-of-state families is often close to sticker cost.",
      provenance: REAL_PROV("financial aid", "214777"),
    },
    provenance: REAL_PROV("institution", "214777"),
    isSample: false,
  },
  {
    id: "135726",
    name: "University of Miami",
    city: "Coral Gables", state: "FL", zip: "33124",
    latitude: 25.7174, longitude: -80.2781,
    website: "https://www.miami.edu",
    admissionsUrl: "https://admissions.miami.edu",
    netPriceCalculatorUrl: null,
    ownership: "private_nonprofit", level: "four_year",
    enrollment: 12900, campusSetting: "suburban", ncaaDivision: "I",
    acceptanceRate: 0.19,
    act25: 31, act75: 34, sat25: 1350, sat75: 1480,
    testPolicy: "optional",
    graduationRate: 0.84, retentionRate: 0.92,
    tuitionInState: 57200, tuitionOutState: 57200,
    fees: null, housingMeals: 16500, books: null, transportation: null, personalExpenses: null,
    avgNetPrice: 39000,
    netPriceByIncome: null,
    avgGrantAid: null, medianFederalDebt: null, medianEarnings10yr: 72000,
    majors: ["Business", "Biology", "Nursing", "Engineering", "Psychology", "Communications", "Marine Science", "Economics"],
    majorShares: null,
    demographics: { white: 0.39, hispanic: 0.28, non_resident: 0.11, black: 0.07, asian: 0.07, two_or_more: 0.04, unknown: 0.04 },
    genderShares: { men: 0.46, women: 0.54 },
    pellGrantRate: 0.15,
    applicationFee: 70,
    deadlines: [
      rdl("135726", "early_decision", "Early Decision I application", "2026-11-01", "https://admissions.miami.edu"),
      rdl("135726", "early_action", "Early Action application", "2026-11-01", "https://admissions.miami.edu"),
      rdl("135726", "early_decision", "Early Decision II application", "2027-01-01", "https://admissions.miami.edu"),
      rdl("135726", "regular", "Regular Decision application", "2027-01-01", "https://admissions.miami.edu"),
    ],
    requirements: [
      ...STD_REQS,
      { key: "css", label: "CSS Profile (for institutional aid)", required: true },
    ],
    financialAid: {
      scholarshipDisplacementPolicy: null,
      requiresFafsa: true, requiresCssProfile: true, priorityAidDeadline: null,
      meetsFullNeed: null, needBlind: null, meritAidAvailable: true,
      notes: "CSS Profile required for institutional need-based aid in addition to the FAFSA.",
      provenance: REAL_PROV("financial aid", "135726"),
    },
    provenance: REAL_PROV("institution", "135726"),
    isSample: false,
  },

  {
    id: "sample-chesapeake-state",
    name: "Chesapeake State University (Sample)",
    city: "Annapolis Ridge",
    state: "MD",
    zip: "21401",
    latitude: 38.99,
    longitude: -76.55,
    website: "https://example.edu/chesapeake-state",
    admissionsUrl: "https://example.edu/chesapeake-state/admissions",
    netPriceCalculatorUrl: "https://example.edu/chesapeake-state/npc",
    ownership: "public",
    level: "four_year",
    enrollment: 28500,
    campusSetting: "suburban",
    ncaaDivision: "I",
    acceptanceRate: 0.52,
    act25: 27, act75: 32, sat25: 1280, sat75: 1450,
    testPolicy: "optional",
    graduationRate: 0.84, retentionRate: 0.93,
    tuitionInState: 9900, tuitionOutState: 37500,
    fees: 2100, housingMeals: 13600, books: 1150, transportation: 1250, personalExpenses: 1900,
    avgNetPrice: 17200,
    netPriceByIncome: { "0_30000": 8900, "30001_48000": 10400, "48001_75000": 14600, "75001_110000": 19800, "110001_plus": 23900 },
    avgGrantAid: 9400, medianFederalDebt: 18500, medianEarnings10yr: 72400,
    majors: ["Computer Science", "Engineering", "Biology", "Business", "Economics", "Nursing", "Psychology"],
    majorShares: sampleShares(["Computer Science", "Engineering", "Biology", "Business", "Economics", "Nursing", "Psychology"]),
    demographics: { white: 0.46, black: 0.24, hispanic: 0.12, asian: 0.09, two_or_more: 0.05, non_resident: 0.03, unknown: 0.01 },
    pellGrantRate: 0.31,
    genderShares: { men: 0.47, women: 0.53 },
    applicationFee: 75,
    deadlines: [
      dl("sample-chesapeake-state", "early_action", "Early Action application", "2026-11-01"),
      dl("sample-chesapeake-state", "regular", "Regular Decision application", "2027-01-20"),
      dl("sample-chesapeake-state", "fafsa", "FAFSA priority filing", "2027-01-15"),
      dl("sample-chesapeake-state", "scholarship", "Merit scholarship consideration", "2026-11-01"),
    ],
    requirements: STD_REQS,
    financialAid: {
      scholarshipDisplacementPolicy: "Outside scholarships reduce unmet need, then loans and work-study, before any university grant is reduced. Displacement of need-based grants is prohibited for Maryland public institutions.",
      requiresFafsa: true, requiresCssProfile: false, priorityAidDeadline: "2027-01-15",
      meetsFullNeed: false, needBlind: true, meritAidAvailable: true,
      notes: "Automatic merit review with Early Action application.",
      provenance: SAMPLE_PROV("financial aid"),
    },
    provenance: SAMPLE_PROV("institution"),
    isSample: true,
  },
  {
    id: "sample-harborlight",
    name: "Harborlight University (Sample)",
    city: "New Haven Point",
    state: "CT",
    zip: "06510",
    latitude: 41.31, longitude: -72.92,
    website: "https://example.edu/harborlight",
    admissionsUrl: "https://example.edu/harborlight/admissions",
    netPriceCalculatorUrl: "https://example.edu/harborlight/npc",
    ownership: "private_nonprofit",
    level: "four_year",
    enrollment: 6600,
    campusSetting: "urban",
    ncaaDivision: "I",
    acceptanceRate: 0.06,
    act25: 33, act75: 35, sat25: 1500, sat75: 1560,
    testPolicy: "optional",
    graduationRate: 0.96, retentionRate: 0.99,
    tuitionInState: 64700, tuitionOutState: 64700,
    fees: 1200, housingMeals: 18500, books: 1000, transportation: 800, personalExpenses: 2100,
    avgNetPrice: 20100,
    netPriceByIncome: { "0_30000": 2900, "30001_48000": 3600, "48001_75000": 8200, "75001_110000": 15800, "110001_plus": 43200 },
    avgGrantAid: 62300, medianFederalDebt: 12000, medianEarnings10yr: 98600,
    majors: ["Computer Science", "Economics", "Political Science", "Biology", "History", "Mathematics"],
    majorShares: sampleShares(["Computer Science", "Economics", "Political Science", "Biology", "History", "Mathematics"]),
    demographics: { white: 0.41, asian: 0.18, hispanic: 0.14, black: 0.09, two_or_more: 0.06, non_resident: 0.11, unknown: 0.01 },
    pellGrantRate: 0.17,
    genderShares: { men: 0.48, women: 0.52 },
    applicationFee: 80,
    deadlines: [
      dl("sample-harborlight", "early_decision", "Early Decision application", "2026-11-01"),
      dl("sample-harborlight", "regular", "Regular Decision application", "2027-01-02"),
      dl("sample-harborlight", "css", "CSS Profile (ED)", "2026-11-10"),
      dl("sample-harborlight", "fafsa", "FAFSA (RD)", "2027-02-01"),
    ],
    requirements: [
      ...STD_REQS,
      { key: "supplemental_essays", label: "Supplemental essays (3)", required: true },
      { key: "css", label: "CSS Profile", required: true },
      { key: "interview", label: "Alumni interview", detail: "Offered where available", required: false },
    ],
    financialAid: {
      scholarshipDisplacementPolicy: "Outside awards first replace the student employment and summer-work expectation; institutional grants are reduced only after those are fully replaced.",
      requiresFafsa: true, requiresCssProfile: true, priorityAidDeadline: "2027-02-01",
      meetsFullNeed: true, needBlind: true, meritAidAvailable: false,
      notes: "Need-based aid only; no merit scholarships.",
      provenance: SAMPLE_PROV("financial aid"),
    },
    provenance: SAMPLE_PROV("institution"),
    isSample: true,
  },
  {
    id: "sample-blue-ridge-tech",
    name: "Blue Ridge Institute of Technology (Sample)",
    city: "Roanoke Gap",
    state: "VA",
    zip: "24011",
    latitude: 37.27, longitude: -79.94,
    website: "https://example.edu/blue-ridge-tech",
    admissionsUrl: "https://example.edu/blue-ridge-tech/admissions",
    netPriceCalculatorUrl: "https://example.edu/blue-ridge-tech/npc",
    ownership: "public",
    level: "four_year",
    enrollment: 34200,
    campusSetting: "rural",
    ncaaDivision: "I",
    acceptanceRate: 0.57,
    act25: 26, act75: 32, sat25: 1240, sat75: 1430,
    testPolicy: "optional",
    graduationRate: 0.86, retentionRate: 0.92,
    tuitionInState: 12100, tuitionOutState: 34800,
    fees: 2600, housingMeals: 11900, books: 1100, transportation: 1400, personalExpenses: 2000,
    avgNetPrice: 19800,
    netPriceByIncome: { "0_30000": 11200, "30001_48000": 13100, "48001_75000": 17400, "75001_110000": 22100, "110001_plus": 25600 },
    avgGrantAid: 7800, medianFederalDebt: 21000, medianEarnings10yr: 78900,
    majors: ["Engineering", "Computer Science", "Architecture", "Business", "Agriculture"],
    majorShares: sampleShares(["Engineering", "Computer Science", "Architecture", "Business", "Agriculture"]),
    demographics: { white: 0.58, black: 0.11, hispanic: 0.10, asian: 0.12, two_or_more: 0.05, non_resident: 0.03, unknown: 0.01 },
    pellGrantRate: 0.24,
    genderShares: { men: 0.61, women: 0.39 },
    applicationFee: 60,
    deadlines: [
      dl("sample-blue-ridge-tech", "early_action", "Early Action application", "2026-11-15"),
      dl("sample-blue-ridge-tech", "regular", "Regular Decision application", "2027-01-15"),
      dl("sample-blue-ridge-tech", "fafsa", "FAFSA priority filing", "2027-03-01"),
    ],
    requirements: STD_REQS.filter((r) => r.key !== "recommendations"),
    financialAid: {
      scholarshipDisplacementPolicy: "Outside scholarships reduce loans first. Institutional grants are only reduced if total aid would exceed the cost of attendance.",
      requiresFafsa: true, requiresCssProfile: false, priorityAidDeadline: "2027-03-01",
      meetsFullNeed: false, needBlind: true, meritAidAvailable: true,
      provenance: SAMPLE_PROV("financial aid"),
    },
    provenance: SAMPLE_PROV("institution"),
    isSample: true,
  },
  {
    id: "sample-elmwood",
    name: "Elmwood College (Sample)",
    city: "Elmwood",
    state: "PA",
    zip: "17603",
    latitude: 40.04, longitude: -76.31,
    website: "https://example.edu/elmwood",
    admissionsUrl: "https://example.edu/elmwood/admissions",
    netPriceCalculatorUrl: "https://example.edu/elmwood/npc",
    ownership: "private_nonprofit",
    level: "four_year",
    enrollment: 2300,
    campusSetting: "suburban",
    ncaaDivision: "III",
    acceptanceRate: 0.64,
    act25: 25, act75: 30, sat25: 1180, sat75: 1370,
    testPolicy: "optional",
    graduationRate: 0.81, retentionRate: 0.88,
    tuitionInState: 58200, tuitionOutState: 58200,
    fees: 400, housingMeals: 14100, books: 1000, transportation: 900, personalExpenses: 1700,
    avgNetPrice: 27400,
    netPriceByIncome: { "0_30000": 16800, "30001_48000": 18900, "48001_75000": 23200, "75001_110000": 28800, "110001_plus": 36100 },
    avgGrantAid: 38600, medianFederalDebt: 24500, medianEarnings10yr: 61200,
    majors: ["Psychology", "Biology", "English", "Business", "Computer Science", "Studio Art"],
    majorShares: sampleShares(["Psychology", "Biology", "English", "Business", "Computer Science", "Studio Art"]),
    demographics: { white: 0.66, hispanic: 0.11, black: 0.08, asian: 0.06, two_or_more: 0.05, non_resident: 0.03, unknown: 0.01 },
    pellGrantRate: 0.28,
    genderShares: { men: 0.42, women: 0.58 },
    applicationFee: 0,
    deadlines: [
      dl("sample-elmwood", "early_decision", "Early Decision application", "2026-11-15"),
      dl("sample-elmwood", "early_action", "Early Action application", "2026-12-01"),
      dl("sample-elmwood", "regular", "Regular Decision application", "2027-02-01"),
      dl("sample-elmwood", "fafsa", "FAFSA priority filing", "2027-02-15"),
      dl("sample-elmwood", "css", "CSS Profile", "2027-02-15"),
    ],
    requirements: [
      ...STD_REQS,
      { key: "supplemental_essays", label: "Supplemental essay (1)", required: true },
      { key: "css", label: "CSS Profile", required: true },
      { key: "interview", label: "Optional interview", required: false },
    ],
    financialAid: {
      scholarshipDisplacementPolicy: "Outside scholarships stack with merit awards up to full tuition; beyond that, college grants are reduced dollar-for-dollar.",
      requiresFafsa: true, requiresCssProfile: true, priorityAidDeadline: "2027-02-15",
      meetsFullNeed: false, needBlind: false, meritAidAvailable: true,
      notes: "Merit awards up to half tuition; no separate application.",
      provenance: SAMPLE_PROV("financial aid"),
    },
    provenance: SAMPLE_PROV("institution"),
    isSample: true,
  },
  {
    id: "sample-monocacy-cc",
    name: "Monocacy Community College (Sample)",
    city: "Frederick Crossing",
    state: "MD",
    zip: "21701",
    latitude: 39.41, longitude: -77.41,
    website: "https://example.edu/monocacy-cc",
    admissionsUrl: "https://example.edu/monocacy-cc/admissions",
    netPriceCalculatorUrl: "https://example.edu/monocacy-cc/npc",
    ownership: "public",
    level: "two_year",
    enrollment: 6100,
    campusSetting: "suburban",
    ncaaDivision: null,
    acceptanceRate: 1.0,
    act25: null, act75: null, sat25: null, sat75: null,
    testPolicy: "blind",
    graduationRate: 0.34, retentionRate: 0.68,
    tuitionInState: 4300, tuitionOutState: 9100,
    fees: 600, housingMeals: null, books: 1300, transportation: 1900, personalExpenses: 1600,
    avgNetPrice: 7400,
    netPriceByIncome: { "0_30000": 4100, "30001_48000": 5200, "48001_75000": 7100, "75001_110000": 8600, "110001_plus": 9300 },
    avgGrantAid: 3100, medianFederalDebt: 8200, medianEarnings10yr: 44800,
    majors: ["Nursing", "Business", "Computer Science", "Cybersecurity", "General Studies"],
    majorShares: sampleShares(["Nursing", "Business", "Computer Science", "Cybersecurity", "General Studies"]),
    demographics: { white: 0.39, black: 0.28, hispanic: 0.18, asian: 0.08, two_or_more: 0.04, unknown: 0.03 },
    pellGrantRate: 0.44,
    genderShares: { men: 0.41, women: 0.59 },
    applicationFee: 0,
    deadlines: [
      dl("sample-monocacy-cc", "rolling", "Rolling admission — apply anytime", null),
      dl("sample-monocacy-cc", "fafsa", "FAFSA priority filing", "2027-03-01"),
      dl("sample-monocacy-cc", "scholarship", "Foundation scholarships", "2027-03-15"),
    ],
    requirements: [
      { key: "application", label: "Application form", required: true },
      { key: "transcript", label: "Official transcript", required: true },
      { key: "fafsa", label: "FAFSA", required: true },
    ],
    financialAid: {
      scholarshipDisplacementPolicy: "Outside scholarships never reduce college aid unless combined aid exceeds the cost of attendance.",
      requiresFafsa: true, requiresCssProfile: false, priorityAidDeadline: "2027-03-01",
      meetsFullNeed: null, needBlind: null, meritAidAvailable: true,
      provenance: SAMPLE_PROV("financial aid"),
    },
    provenance: SAMPLE_PROV("institution"),
    isSample: true,
  },
  {
    id: "sample-piedmont",
    name: "Piedmont University (Sample)",
    city: "Charlotte Mills",
    state: "NC",
    zip: "28202",
    latitude: 35.23, longitude: -80.84,
    website: "https://example.edu/piedmont",
    admissionsUrl: "https://example.edu/piedmont/admissions",
    netPriceCalculatorUrl: "https://example.edu/piedmont/npc",
    ownership: "private_nonprofit",
    level: "four_year",
    enrollment: 8900,
    campusSetting: "urban",
    ncaaDivision: "I",
    acceptanceRate: 0.21,
    act25: 31, act75: 34, sat25: 1420, sat75: 1520,
    testPolicy: "optional",
    graduationRate: 0.91, retentionRate: 0.96,
    tuitionInState: 61800, tuitionOutState: 61800,
    fees: 900, housingMeals: 16200, books: 1100, transportation: 1000, personalExpenses: 1900,
    avgNetPrice: 31900,
    netPriceByIncome: { "0_30000": 9800, "30001_48000": 12400, "48001_75000": 18700, "75001_110000": 27900, "110001_plus": 46800 },
    avgGrantAid: 44200, medianFederalDebt: 17500, medianEarnings10yr: 88300,
    majors: ["Business", "Economics", "Computer Science", "Communications", "Biology"],
    majorShares: sampleShares(["Business", "Economics", "Computer Science", "Communications", "Biology"]),
    demographics: { white: 0.55, black: 0.13, hispanic: 0.09, asian: 0.10, two_or_more: 0.06, non_resident: 0.06, unknown: 0.01 },
    pellGrantRate: 0.19,
    genderShares: { men: 0.46, women: 0.54 },
    applicationFee: 85,
    deadlines: [
      dl("sample-piedmont", "early_decision", "Early Decision I", "2026-11-15"),
      dl("sample-piedmont", "early_decision", "Early Decision II", "2027-01-15"),
      dl("sample-piedmont", "regular", "Regular Decision application", "2027-01-15"),
      dl("sample-piedmont", "css", "CSS Profile", "2027-02-01"),
      dl("sample-piedmont", "fafsa", "FAFSA", "2027-02-01"),
    ],
    requirements: [
      ...STD_REQS,
      { key: "supplemental_essays", label: "Supplemental essays (2)", required: true },
      { key: "css", label: "CSS Profile", required: true },
      { key: "interview", label: "Evaluative interview", detail: "Strongly recommended", required: false },
    ],
    financialAid: {
      scholarshipDisplacementPolicy: "Outside awards reduce the loan and work expectation first; need-based grants may be reduced once loans are eliminated.",
      requiresFafsa: true, requiresCssProfile: true, priorityAidDeadline: "2027-02-01",
      meetsFullNeed: true, needBlind: false, meritAidAvailable: true,
      provenance: SAMPLE_PROV("financial aid"),
    },
    provenance: SAMPLE_PROV("institution"),
    isSample: true,
  },
  {
    id: "sample-cascadia",
    name: "Cascadia State University (Sample)",
    city: "Bellham",
    state: "WA",
    zip: "98225",
    latitude: 48.73, longitude: -122.49,
    website: "https://example.edu/cascadia",
    admissionsUrl: "https://example.edu/cascadia/admissions",
    netPriceCalculatorUrl: "https://example.edu/cascadia/npc",
    ownership: "public",
    level: "four_year",
    enrollment: 15800,
    campusSetting: "urban",
    ncaaDivision: "II",
    acceptanceRate: 0.9,
    act25: 20, act75: 27, sat25: 1050, sat75: 1260,
    testPolicy: "blind",
    graduationRate: 0.68, retentionRate: 0.8,
    tuitionInState: 8600, tuitionOutState: 26400,
    fees: 1100, housingMeals: 14400, books: 1000, transportation: 1300, personalExpenses: 2200,
    avgNetPrice: 15900,
    netPriceByIncome: { "0_30000": 9100, "30001_48000": 10800, "48001_75000": 14200, "75001_110000": 18400, "110001_plus": 21700 },
    avgGrantAid: 6900, medianFederalDebt: 19800, medianEarnings10yr: 56700,
    majors: ["Environmental Science", "Computer Science", "Education", "Business", "Marine Biology", "Psychology"],
    majorShares: sampleShares(["Environmental Science", "Computer Science", "Education", "Business", "Marine Biology", "Psychology"]),
    demographics: { white: 0.52, hispanic: 0.14, asian: 0.13, black: 0.05, two_or_more: 0.08, aian: 0.02, nhpi: 0.02, non_resident: 0.03, unknown: 0.01 },
    pellGrantRate: 0.36,
    genderShares: { men: 0.45, women: 0.55 },
    applicationFee: 60,
    deadlines: [
      dl("sample-cascadia", "priority", "Priority application", "2027-01-31"),
      dl("sample-cascadia", "rolling", "Rolling admission after priority date", null),
      dl("sample-cascadia", "fafsa", "FAFSA priority filing", "2027-01-31"),
    ],
    requirements: [
      { key: "application", label: "Application form", required: true },
      { key: "fee", label: "Application fee or waiver", required: true },
      { key: "essay", label: "Personal essay", required: true },
      { key: "transcript", label: "Official transcript", required: true },
      { key: "fafsa", label: "FAFSA", required: true },
    ],
    financialAid: {
      scholarshipDisplacementPolicy: "Outside scholarships reduce self-help aid (loans/work-study) before any grant reduction, per state policy for public institutions.",
      requiresFafsa: true, requiresCssProfile: false, priorityAidDeadline: "2027-01-31",
      meetsFullNeed: false, needBlind: true, meritAidAvailable: true,
      provenance: SAMPLE_PROV("financial aid"),
    },
    provenance: SAMPLE_PROV("institution"),
    isSample: true,
  },
];
